/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ModemCard: typeof import('./src/components/ModemCard.vue')['default']
    ModemItem: typeof import('./src/components/ModemItem.vue')['default']
    OperationError: typeof import('./src/components/common/OperationError.vue')['default']
    SpinningLogo: typeof import('./src/components/common/SpinningLogo.vue')['default']
  }
}
