name: Deploy BlueOS Extension Image

on:
  push:
  # Run manually
  workflow_dispatch:
  # NOTE: caches may be removed if not run weekly
  #  -> may be worth scheduling for every 6 days

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy BlueOS Extension
        uses: BlueOS-community/Deploy-BlueOS-Extension@v1.0.1
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: 'cellphone-modem-manager'

      - name: Build and Publish Extension in BlueOS Cloud
        uses: bluerobotics/blueos-cloud-action@0.0.3
        with:
          BCLOUD_PAT: ${{ secrets.BCLOUD_PAT }}
          EXTENSION: 441a2bc1-b47f-4926-bd4b-c797dbc72efe
